#!/usr/bin/env python3
"""
Regenerate the coverage dashboard in README.md from the repository itself.
Counts are real; nothing here is hand-written. Run after every layer sweep.
"""
import os, sys, glob, re
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(ROOT)
README = os.path.join(REPO, "README.md")


def load(p, d=None):
    if not os.path.exists(p):
        return d
    with open(p) as f:
        return yaml.safe_load(f) or d


def main():
    vocab = load(os.path.join(ROOT, "schema", "vocab.yaml"))
    layers = vocab["layers"]

    nodes = {}
    for p in glob.glob(os.path.join(ROOT, "nodes", "**", "*.yaml"), recursive=True):
        n = load(p)
        if isinstance(n, dict) and n.get("id"):
            nodes[n["id"]] = n

    edges = (load(os.path.join(ROOT, "edges", "edges.yaml"), {}) or {}).get("edges", [])
    gaps = (load(os.path.join(ROOT, "gaps", "gaps.yaml"), {}) or {}).get("gaps", [])
    slogs = (load(os.path.join(ROOT, "gaps", "search_log.yaml"), {}) or {}).get("searches", [])
    refs = (load(os.path.join(ROOT, "sources", "bibliography.yaml"), {}) or {}).get("refs", {})

    # per-layer tallies
    rows, tot = [], {"n": 0, "f": 0, "e": 0, "g": 0}
    edge_layer = {}
    for e in edges:
        src = nodes.get(e.get("source"), {})
        L = src.get("layer")
        edge_layer[L] = edge_layer.get(L, 0) + 1

    for L in sorted(layers, key=lambda x: int(x[1:])):
        ln = [n for n in nodes.values() if n.get("layer") == L]
        full = [n for n in ln if not n.get("stub")]
        lg = [g for g in gaps if g.get("layer") == L]
        hard = [g for g in lg if g.get("type") in ("search_established", "quantitative_gap")]
        le = edge_layer.get(L, 0)
        doc = os.path.join(ROOT, "docs", f"{L}_{layers[L]}.md")
        has_doc = "✅" if os.path.exists(doc) else "—"
        fig = glob.glob(os.path.join(ROOT, "figures", f"{L}_*.mmd"))
        quota = "✅" if (len(lg) >= 8 and len(hard) >= 3) else f"{len(lg)}/8·{len(hard)}/3"
        rows.append(f"| {L} | {layers[L]} | {len(ln)} | {len(full)} | {le} | "
                    f"{len(lg)} | {quota} | {has_doc} | {'✅' if fig else '—'} |")
        tot["n"] += len(ln); tot["f"] += len(full); tot["e"] += le; tot["g"] += len(lg)

    conf = {}
    for n in nodes.values():
        if not n.get("stub"):
            conf[n.get("confidence")] = conf.get(n.get("confidence"), 0) + 1
    conf_line = " · ".join(f"**{k}** {conf[k]}" for k in sorted(conf)) or "_none yet_"

    gt = {}
    for g in gaps:
        gt[g.get("type")] = gt.get(g.get("type"), 0) + 1
    gt_line = " · ".join(f"`{k}` {v}" for k, v in sorted(gt.items())) or "_none yet_"

    nq = sum(len(n.get("quantitative") or []) for n in nodes.values())
    csvp = os.path.join(ROOT, "quant", "parameters.csv")
    ncsv = 0
    if os.path.exists(csvp):
        with open(csvp) as f:
            ncsv = max(0, sum(1 for _ in f) - 1)

    vr = load(os.path.join(ROOT, "sources", "verification_report.yaml"), {}) or {}
    vc = vr.get("counts", {})
    vline = (f"{vc.get('ok',0)} verified · {vc.get('mismatch',0)} mismatched · "
             f"{vc.get('unresolved',0)} unresolved · {vc.get('no_identifier',0)} manual"
             if vc else "_not yet run_")

    targets = {"nodes": 1200, "edges": 2500, "gaps": 150}
    def bar(v, t):
        pct = min(100, int(100 * v / t))
        return f"{'█' * (pct // 5)}{'░' * (20 - pct // 5)} {v}/{t} ({pct}%)"

    md = f"""**Totals** — {tot['n']} nodes ({tot['f']} researched, {tot['n']-tot['f']} stubs) ·
{len(edges)} edges · {len(gaps)} gaps ({len(slogs)} search logs) · {len(refs)} references

```
nodes  {bar(tot['n'], targets['nodes'])}
edges  {bar(len(edges), targets['edges'])}
gaps   {bar(len(gaps), targets['gaps'])}
```

| Layer | Name | Nodes | Researched | Edges out | Gaps | Quota | Doc | Fig |
|---|---|---:|---:|---:|---:|:--:|:--:|:--:|
{chr(10).join(rows)}
| | **total** | **{tot['n']}** | **{tot['f']}** | **{len(edges)}** | **{tot['g']}** | | | |

**Confidence distribution** (researched nodes): {conf_line}

**Gap types**: {gt_line}

**Quantitative**: {nq} values on nodes · {ncsv} rows in `quant/parameters.csv`

**Reference verification** (`tools/verify_refs.py`): {vline}

_Quota column: ≥8 gaps per layer, ≥3 of which are `search_established` or
`quantitative_gap`. Generated by `atlas/tools/dashboard.py`._"""

    with open(README) as f:
        txt = f.read()
    new = re.sub(r"<!-- DASHBOARD:BEGIN -->.*?<!-- DASHBOARD:END -->",
                 "<!-- DASHBOARD:BEGIN -->\n" + md + "\n<!-- DASHBOARD:END -->",
                 txt, flags=re.S)
    with open(README, "w") as f:
        f.write(new)
    print(md)


if __name__ == "__main__":
    sys.exit(main())
