print("=== THE DECISIVE COMPARISON: TWO WAYS TO HAVE NO OESTROGEN ===\n")
print("A) 17OHD - ZERO oestrogen AND ZERO androgen, chronically ill")
print("   n=51 adults (27 XY, 24 XX), complete sex-steroid absence FROM BIRTH")
print("   median final height 170 cm (range 154-191), Z = +1.3")
print("   ALL BUT ONE of 42 exceeded mid-parental target")
print("   MAXIMUM 191 cm. NO PATIENT EXCEEDED 195 cm.")
print("   authors' stated limiters: impaired cortisol, uncontrolled hypertension, infection\n")
print("B) AROMATASE DEFICIENCY / ERa-null - ZERO oestrogen, HIGH androgen, otherwise healthy")
print("   190 cm, 204 cm, one at 6'8\" (203 cm)")
print("   +5 cm over 6 years IN ADULTHOOD; ESR1-null still gaining in his THIRD DECADE")
print("   bone age 15 at ~28 yr; unfused epiphyses at 31\n")
print("=== WHAT SEPARATES THEM ===")
print("   17OHD lacks oestrogen AND androgen, and is a hypertensive CAH with cortisol failure.")
print("   Aromatase deficiency lacks ONLY oestrogen - testosterone is normal-to-HIGH")
print("   because it cannot be converted. Otherwise healthy.")
print("   => THE TALL PHENOTYPE REQUIRES: zero oestrogen + PRESERVED ANDROGEN + health.\n")
print("=== AND THAT IS EXACTLY WHAT AN AROMATASE INHIBITOR DOES ===")
print("   AI blocks T -> E2. E2 falls, T RISES (substrate accumulates).")
print("   Anastrozole reproduces the AROMATASE-DEFICIENCY configuration,")
print("   NOT the 17OHD configuration. The stack already has the right one.\n")
print("=== SO: IS THE POOL BIGGER? ===")
tgt=195.6
print(f"   normal male mean ~176 cm. 17OHD median 170 but Z=+1.3 vs target, in a SICK cohort.")
print(f"   healthy oestrogen-null men: 190-204 cm, growing into the 3rd decade.")
print(f"   => THE POOL SUPPORTS ~10-25 cm BEYOND WHAT NORMAL CLOSURE DELIVERS.")
print(f"   => BUT IT IS NOT UNLIMITED: 51 people with a decade+ of extra window")
print(f"      topped out at 191, and the two healthiest reached 204.")
print(f"\n   *** 204 cm IS THE EMPIRICAL CEILING OF THE OESTROGEN-REMOVAL LEVER IN HUMANS. ***")
print(f"   *** TARGET {tgt} cm IS BELOW IT (by {204-tgt:.1f} cm). ***\n")
print("=== THE CATCH, STATED PLAINLY ===")
print("   Those men were oestrogen-null FROM BIRTH. The extra height accrued across")
print("   the whole of childhood and adolescence at LOW velocity (+5 cm / 6 yr = 0.83 cm/yr).")
print("   A subject at BA16 has already spent ~16 bone-age years UNDER NORMAL OESTROGEN -")
print("   i.e. most of the window in which that height was banked.")
print("   => oestrogen removal at BA16 buys the TAIL of the phenotype, not the whole of it.")
print("   => and the velocity term is what GH supplies (bone-age-neutral at 0.24-0.37 mg/kg/wk).")
