import sys;sys.path.insert(0,'.')
import q,numpy as np,re
d=q.D('GSE113982');L=[str(x) for x in d['labels']];X=d['X'];gl=[str(g) for g in d['g']]
def G(rx): return [i for i,l in enumerate(L) if re.search(rx,l)]
RZy,RZo=G(r'^p[23]_R'),G(r'^p28_R');PZy,PZo=G(r'^p[23]_P'),G(r'^p28_P')
ex=np.nanmax(X,axis=1);ok=ex>np.nanpercentile(ex,50)
def bg(a,b):
    v=np.nanmean(X[:,a],axis=1)-np.nanmean(X[:,b],axis=1);return v,float(np.nanmean(v[ok]))
vR,bR=bg(RZo,RZy); vP,bP=bg(PZo,PZy)
AX={
'THYROID (T3) - local activation':'DIO2 DIO3 THRA THRB SLC16A2 SLC16A10 CRYM',
'GLUCOCORTICOID':'NR3C1 HSD11B1 HSD11B2 FKBP5 TSC22D3 KLF15',
'ANDROGEN':'AR SRD5A1 SRD5A2 HSD17B3 CYP17A1',
'OESTROGEN':'ESR1 ESR2 GPER1 CYP19A1 HSD17B1',
'VITAMIN D':'VDR CYP27B1 CYP24A1 RXRA',
'RETINOIC ACID':'RARA RARB RARG RXRA RXRB CYP26A1 CYP26B1 ALDH1A1 ALDH1A2 ALDH1A3 CRABP1 CRABP2 STRA6 RBP4',
'CNP / NPR2 / cGMP':'NPPC NPR2 NPR3 PRKG1 PRKG2 PDE5A GUCY1A1',
'FGF':'FGFR1 FGFR2 FGFR3 FGF2 FGF9 FGF18 SPRY1 SPRY2 SPRY4 DUSP6',
'GH / IGF':'GHR IGF1 IGF2 IGF1R IGFBP2 IGFBP3 IGFBP4 IGFBP5 IGFBP6 STAT5B SOCS2 PAPPA PAPPA2 STC2',
'PTHrP / PTH1R':'PTHLH PTH1R GNAS PRKACA CREB1 SIK3',
'WNT':'WNT4 WNT5A WNT5B WNT16 AXIN2 LEF1 TCF7 SFRP1 SFRP2 SFRP4 SFRP5 FRZB DKK1 DKK3 WIF1 NOTUM LRP5 LRP6',
'BMP':'BMP2 BMP4 BMP5 BMP6 BMP7 GDF5 NOG GREM1 CHRDL1 CHRDL2 SMAD1 SMAD5 ID1 ID2 ID3',
'TGF-beta':'TGFB1 TGFB2 TGFB3 TGFBR1 TGFBR2 TGFBR3 SMAD2 SMAD3 SMAD7 LTBP1 LTBP2 THBS1',
'NOTCH':'NOTCH1 NOTCH2 NOTCH3 JAG1 JAG2 DLL1 DLL4 HES1 HEY1 HEYL RBPJ',
'HIPPO/YAP':'YAP1 WWTR1 TEAD1 TEAD2 CTGF CYR61 AMOTL2 LATS1 LATS2 NF2',
'mTOR / nutrient':'MTOR RPTOR RICTOR AKT1 TSC1 TSC2 RPS6KB1 EIF4EBP1 DEPTOR SESN2',
'AMPK / energy':'PRKAA1 PRKAA2 PRKAB1 STK11 PPARGC1A SIRT1 NAMPT',
'HYPOXIA':'HIF1A EPAS1 VHL EGLN1 EGLN2 EGLN3 VEGFA SLC2A1 PGK1 LDHA BNIP3 P4HA1',
'PRIMARY CILIUM':'IFT80 IFT88 KIF3A TTC21B EVC EVC2 ARL13B PKD1 PKD2 BBS1',
'AUTOPHAGY':'ATG5 ATG7 BECN1 MAP1LC3B SQSTM1 TFEB LAMP1 CTSK',
'SENESCENCE/SASP':'CDKN2A CDKN1A TP53 SERPINE1 IL6 MMP3 GLB1 LMNB1 TERT',
'IMPRINTED NETWORK':'IGF2 H19 DLK1 MEG3 MEST PEG3 ZIM1 PLAGL1 CDKN1C IGF2R NDN GPC3 GRB10 PEG10 NNAT SGCE SLC38A4 PHLDA2 IMPACT NAP1L5 PPP1R9A',
'HEDGEHOG receptor-side':'SMO PTCH1 PTCH2 GLI1 GLI2 GLI3 SUFU',
'HEDGEHOG ligand-side':'IHH SHH DHH BOC CDON GAS1 HHIP DISP1 SCUBE1 SCUBE2 SCUBE3 GPC3 GPC5',
}
print('EVERY DRUGGABLE AXIS, SCORED IN THE POOL COMPARTMENT (P28 minus P2/P3, above background)')
print('%-34s %9s %9s %9s'%('axis','RESTING','prolif','RZ-minus-PZ'))
print('-'*66)
rows=[]
for nm,s in AX.items():
    gs=set(s.split());
    r=[vR[k] for k,g in enumerate(gl) if g in gs and ok[k] and np.isfinite(vR[k])]
    p=[vP[k] for k,g in enumerate(gl) if g in gs and ok[k] and np.isfinite(vP[k])]
    if len(r)<4: continue
    R_=np.mean(r)-bR; P_=np.mean(p)-bP
    rows.append((nm,R_,P_,R_-P_,len(r)))
for nm,R_,P_,D_,n in sorted(rows,key=lambda x:x[1]):
    print('%-34s %9.2f %9.2f %9.2f  (n=%d)'%(nm,R_,P_,D_,n))
